version: '3.8'

services:

  app:
    build:
      context: .
    env_file: .env
    depends_on:
      - redis_service

  redis_service:
    image: redis:7.0.4
    command: redis-server --save 60 1 --loglevel warning
